"""change data nullable

Revision ID: 35964710e4b0
Revises: 044e2f6f80bc
Create Date: 2024-07-15 19:41:30.700450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35964710e4b0'
down_revision = '044e2f6f80bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
