"""change book models

Revision ID: 5a17e3fb3e0f
Revises: e7d0bb720100
Create Date: 2024-07-15 19:30:52.845315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a17e3fb3e0f'
down_revision = 'e7d0bb720100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ISBN', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('publisher', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=128), nullable=False))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_column('image_url')
        batch_op.drop_column('publisher')
        batch_op.drop_column('year')
        batch_op.drop_column('author')
        batch_op.drop_column('ISBN')

    # ### end Alembic commands ###
