"""change is_return and add cascade

Revision ID: d0dfd9bc93dc
Revises: 8482389daa04
Create Date: 2024-07-16 10:35:26.225824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0dfd9bc93dc'
down_revision = '8482389daa04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_return', sa.Boolean(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_return')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_return', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('is_return')

    # ### end Alembic commands ###
